version: '3'
services:
  webserver:
    container_name: webserver
    build:
      context: ./nginx
    volumes:
      - ./bookble:/var/www/vhosts/bookble
      - ./trim-be:/var/www/vhosts/trim-be
      - ./factsonfactsbot:/var/www/vhosts/factsonfactsbot
      - ./newsondemandbot:/var/www/vhosts/newsondemandbot
      - ./politicalnewsbot:/var/www/vhosts/politicalnewsbot
      - ./certbot:/var/www/certbot
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
     - bookble
     - trim-be
     - factsonfactsbot
     - newsondemandbot
     - politicalnewsbot
    networks:
      - appnet
      - botnet
  bookble:
    container_name: bookble
    image: olamileke/bookble
    ports:
      - "3000:3000"
    volumes:
      - ./bookble:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - appnet
  trim-be:
    container_name: trim-be
    build:
      context: ./trim-be
    ports:
      - "5000:5000"
    volumes:
      - ./trim-be:/app
    networks:
      - appnet
  trim-db:
    container_name: trim-db
    image: postgres
    environment:
      POSTGRES_USER: olamileke
      POSTGRES_DB: trim
      POSTGRES_PASSWORD: 8gKgLoaMB4o4vhDsIEAd
    ports:
      - "5432:5432"
    volumes:
      - ./trim-db:/var/lib/posgresql/data
    networks:
      - appnet
  factsonfactsbot:
    container_name: factsonfactsbot
    build:
      context: ./factsonfactsbot
    volumes:
      - ./factsonfactsbot:/factsonfactsbot
    networks:
      - botnet
  newsondemandbot:
    container_name: newsondemandbot
    build:
      context: ./newsondemandbot
    volumes:
      - ./newsondemandbot:/newsondemandbot
    networks:
      - botnet
  politicalnewsbot:
    container_name: politicalnewsbot
    build:
      context: ./politicalnewsbot
    volumes:
      - ./politicalnewsbot:/politicalnewsbot
    networks:
      - botnet
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   volumes:
  #     - ./certbot:/var/www/certbot
  #     - ./certbot-etc:/etc/letsencrypt
  #     - ./certbot-var:/var/lib/letsencrypt
  #   depends_on:
  #     - webserver
  #   networks:
  #     - botnet
  #   command: certonly --webroot --webroot-path=/var/www/certbot --email olamileke.dev@gmail.com --agree-tos --no-eff-email --force-renewal -d bookble.themilestonesapp.xyz
networks:
  appnet:
    driver:
      bridge
  botnet:
    driver:
      bridge