version: '3'
services:
  webserver:
    container_name: webserver
    build:
      context: ./nginx
    volumes:
      - ./certbot/root:/var/www/certbot
      - ./certbot/etc:/etc/letsencrypt
      - ./certbot/var:/var/lib/letsencrypt
      - ./certbot/dhparam:/etc/ssl/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
     - factsonfactsbot
     - newsondemandbot
     - politicalnewsbot
    networks:
      - botnet
  factsonfactsbot:
    container_name: factsonfactsbot
    image: olamileke/factsonfactsbot
    volumes:
      - ./env/factsonfactsbot.env:/factsonfactsbot/.env
    networks:
      - botnet
  newsondemandbot:
    container_name: newsondemandbot
    image: olamileke/newsondemandbot
    volumes:
      - ./env/newsondemandbot.env:/newsondemandbot/.env
    networks:
      - botnet
  politicalnewsbot:
    container_name: politicalnewsbot
    image: olamileke/politicalnewsbot
    volumes:
      - ./env/politicalnewsbot.env:/politicalnewsbot/.env
    networks:
      - botnet
  # certbot:
  #   image: certbot/dns-digitalocean
  #   container_name: certbot
  #   volumes:
  #     - ./certbot/root:/var/www/certbot
  #     - ./certbot/etc:/etc/letsencrypt
  #     - ./certbot/var:/var/lib/letsencrypt
  #     - ./certbot/credentials:/credentials
  #   command: certonly --dns-digitalocean --dns-digitalocean-credentials /credentials/credentials.ini -d bots.olamileke.dev
  #   networks:
  #     - botnet
networks:
  botnet:
    driver:
      bridge